# Copyright (c) 2023-2025 Christian Hinkle, Brian Hinkle.

# Set this variable for the person including us to use.
set(FILES_CMAKE_RESULT
  # List out all our include files.
  "${CMAKE_CURRENT_SOURCE_DIR}/Files/${MY_BASE_PROJECT_NAME_FULL}_Export.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/Files/${MY_BASE_PROJECT_NAME_FULL}_include_export.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/Files/${MY_BASE_PROJECT_NAME_NAMESPACE}/${MY_BASE_PROJECT_NAME_LEAFNAME}/Filesystem.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/Files/${MY_BASE_PROJECT_NAME_NAMESPACE}/${MY_BASE_PROJECT_NAME_LEAFNAME}/String.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/Files/${MY_BASE_PROJECT_NAME_NAMESPACE}/${MY_BASE_PROJECT_NAME_LEAFNAME}/String.inl"
  "${CMAKE_CURRENT_SOURCE_DIR}/Files/${MY_BASE_PROJECT_NAME_NAMESPACE}/${MY_BASE_PROJECT_NAME_LEAFNAME}/CharBufferString.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/Files/${MY_BASE_PROJECT_NAME_NAMESPACE}/${MY_BASE_PROJECT_NAME_LEAFNAME}/DataMixin.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/Files/${MY_BASE_PROJECT_NAME_NAMESPACE}/${MY_BASE_PROJECT_NAME_LEAFNAME}/DataChain.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/Files/${MY_BASE_PROJECT_NAME_NAMESPACE}/${MY_BASE_PROJECT_NAME_LEAFNAME}/TypeTraits.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/Files/${MY_BASE_PROJECT_NAME_NAMESPACE}/${MY_BASE_PROJECT_NAME_LEAFNAME}/FunctionTraits.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/Files/${MY_BASE_PROJECT_NAME_NAMESPACE}/${MY_BASE_PROJECT_NAME_LEAFNAME}/Concepts.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/Files/${MY_BASE_PROJECT_NAME_NAMESPACE}/${MY_BASE_PROJECT_NAME_LEAFNAME}/CommandParsing.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/Files/${MY_BASE_PROJECT_NAME_NAMESPACE}/${MY_BASE_PROJECT_NAME_LEAFNAME}/CommandParsing.inl"
  "${CMAKE_CURRENT_SOURCE_DIR}/Files/${MY_BASE_PROJECT_NAME_NAMESPACE}/${MY_BASE_PROJECT_NAME_LEAFNAME}/ContainerElementType.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/Files/${MY_BASE_PROJECT_NAME_NAMESPACE}/${MY_BASE_PROJECT_NAME_LEAFNAME}/Static_Execute.h"
  )
